CREATE DATABASE  IF NOT EXISTS accounts;
USE accounts;

DROP TABLE IF EXISTS role;
CREATE TABLE role (
  id INTEGER(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INTEGER(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS user_role;
CREATE TABLE user_role (
  user_id int(11) NOT NULL,
  role_id int(11) NOT NULL,
  PRIMARY KEY (user_id, role_id),
  KEY fk_user_role_roleid_idx (role_id),
  CONSTRAINT fk_user_role_roleid FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_user_role_userid FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE
);